### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/concurrency-ri#13]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538671

**Comment by smillidge** [comment]
No problem I don't have the skills to do it but know someone who does ;-)

**Comment by MarkWareham** [comment]
https://jenkins.eclipse.org/cu/job/concurrency-impl-master-build/
