### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/concurrency-ri#14]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by m0mus** [comment]
@smillidge You mentioned that you are working on both concurrency-api and concurrency-ri here: https://github.com/eclipse-ee4j/ee4j/issues/30. Assigning this task to you. :)

**Comment by senivam** [comment]
release job link:
https://jenkins.eclipse.org/cu/job/concurrency-impl-release-build/

**Comment by MarkWareham** [comment]
impl not finished. Awaiting PR merge to API to run API release Job as that is a dependency on this

**Comment by m0mus** [comment]
This is task is for creating a pipeline, not for actual releasing the stuff. Tasks for releasing are coming next. If the release pipeline works this task should be closed.

**Comment by MarkWareham** [comment]
I would prefer to test it fully first. That requires some pom.xml PRs reviewing & merged. There were a few problems with the API release job spotted in testing and I expect there could be here too. Waiting on https://github.com/eclipse-ee4j/concurrency-api/pull/63 and https://github.com/eclipse-ee4j/concurrency-ri/pull/22

**Comment by m0mus** [comment]
@MarkWareham I am fine with it. Just remember that we have a deadline for all CI/CD tasks. And this deadline now is Oct 29. You have to finish your testing before that.

**Comment by MarkWareham** [comment]
Will do. It doesn't help waiting days for PR review for a version number change in pom.

**Comment by MarkWareham** [comment]
Forbidden Access to OSSRH. Logged Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540506

**Comment by m0mus** [comment]
@MarkWareham If you need PRs approval ping me directly be email: dmitry.kornilov@oracle.com.

**Comment by MarkWareham** [comment]
Access now works to OSSRH
